vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')

vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous [D]iagnostic message' })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = 'Go to next [D]iagnostic message' })
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float, { desc = 'Show diagnostic [E]rror messages' })
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<leader>p', ':Ex<CR>', { desc = 'Open File Tree' })

vim.keymap.set('n', 'L', ':bn<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '<C-left>', ':bn<CR>', { desc = 'Next buffer' })

vim.keymap.set('n', 'H', ':bp<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '<C-Right>', ':bp<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '<C-J>', 'mzJ`z')
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv")
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv")
vim.keymap.set('n', '<leader>k', '<cmd>lnext<CR>zz')
vim.keymap.set('n', '<leader>j', '<cmd>lprev<CR>zz')
vim.keymap.set('n', '<C-UP>', '<C-u>zz')
vim.keymap.set('n', '<C-DOWN>', '<C-d>zz')

vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })

vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
vim.keymap.set('n', '<C-w>b', ':bd<cr>', { silent = true, desc = 'close Current Buffer' })
vim.keymap.set('n', '<leader>;', ':TagbarToggle<CR><C-w><C-l>', { desc = 'select all' })
vim.keymap.set('n', '<C-a>', 'ggVG', { desc = 'select all' })
vim.keymap.set('n', '<S-Down>', '2jzz', { desc = 'select all' })
vim.keymap.set('n', '<S-Up>', '2kzz', { desc = 'select all' })
vim.keymap.set('n', '<M-S-1>', ':AsyncRun<Space>', { noremap = true, silent = false })
vim.keymap.set('n', '\\', '<CMD>Oil<CR>', { desc = 'Open parent directory' })
